CHAT_LIST_URI = "/chats/"
CHAT_LISTENERS_URI = "/chats/{chat_oid}/listeners/"
CHAT_INFO_URI = "/chats/{chat_oid}/"
DEFAULT_LIMIT = "10"
DEFAULT_OFFSET = "0"
DELETE_LISTENER_URI = "/chats/{chat_oid}/listeners/{telegram_chat_id}/"